# Use an official Python runtime as a base image
FROM python:3.10

# Define the build argument
ARG API_KEY  

# Optionally, set it as an environment variable
ENV API_KEY=${API_KEY}  

# Set the working directory
WORKDIR /app

# Copy requirements and install them
COPY /requirements.txt .
RUN pip install -r requirements.txt

# Install dependencies
RUN apt-get update && apt-get install -y libgl1
# Copy the rest of the application code
COPY . .

# Expose the port FastAPI will run on
EXPOSE 8000

# Command to run FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
